@TodoApi_HostAddress = http://localhost:5225

POST {{TodoApi_HostAddress}}/Pessoas/1/enderecos
Content-Type: application/json

{
  "logradouro": "santo carvalho",
  "numero": "234",
  "uf": "ES",
  "cidade": "Vitoria",
  "bairro": "Bento ferreira"
}
###

POST {{TodoApi_HostAddress}}/Pessoas
Content-Type: application/json

{
  "nome": "theo fish",
  "idade": 20,
  "email": "theo@gmail.com"
}

###

DELETE {{TodoApi_HostAddress}}/Pessoas/1

###

PUT {{TodoApi_HostAddress}}/Pessoas/1
Content-Type: application/json

{
  "nome": "livia fish",
  "idade": 20,
  "email": "theo@gmail.com"
}

###

DELETE {{TodoApi_HostAddress}}/Pessoas/1/enderecos/1