@TodoApi_HostAddress = http://localhost:5225

DELETE {{TodoApi_HostAddress}}/pessoas/1

###


//Content-Type: application/json
//{
  //"nome": "theo fish",
  //"idade": 20,
  //"email": "theo@gmail.com"
//}

//{
  //"logradouro": "santo agostinho",
  //"numero": "234",
  //"uf": "ES",
  //"cidade": "Vitoria",
  //"bairro": "Bento ferreira"
//}